sudo: required
language: cpp
dist: xenial
before_install:
install:
before_script:
script:
  - ./package.sh ${DISTRIBUTION} ${ARCHITECTURE}
after_failure:
after_success:
env:
  matrix:
    - DISTRIBUTIONS=trusty ARCHITECTURES=i386
    - DISTRIBUTIONS=xenial ARCHITECTURES=i386
    - DISTRIBUTIONS=bionic ARCHITECTURES=i386
    - DISTRIBUTIONS=trusty ARCHITECTURES=amd64
    - DISTRIBUTIONS=xenial ARCHITECTURES=amd64
    - DISTRIBUTIONS=bionic ARCHITECTURES=amd64
